export enum TIME_STAMP{

    LAST_EARN_ARENA_ENERGY  = 101,
    LAST_EARN_BOSS_ENERGY   = 102,
    LAST_SHARE_GAME         = 103,
    LAST_GAIN_SHARE_REWARD  = 104,
    LAST_GAIN_RETURN_REWARD = 105
}